@startuml Part_2

state init #LightBlue
state Operational #lightGreen
[*]-->init: Power on
init--> Operational: auto
Operational-->init: reset

state Stopped #red 
Operational-->Stopped : Fault detected
Operational-->Stopped :emergency Button pressed 

@enduml
